[package]
name = "cute-pics-api"
version = "0.1.0"
edition = "2021"

[profile.ship]
inherits = "release"
debug = 0
lto = 'thin'

[dependencies]
actix-cors = "0.6.3"
actix-web = "4.2.1"
rand = "0.8.5"
