apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cute-pics-api
spec:
  rules:
    - host: cute-pics-api.dcnick3.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cute-pics-api
                port:
                  number: 80
  tls:
    - hosts:
        - cute-pics-api.dcnick3.me
